basic:
    name: 'https://dewereldvankina.stad.gent'
    environments:
        production: 'https://kina.stad.gent/'
        staging: 'https://kina.qa.stad.gent/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: qa, password: assurance }
        development: { user: '', password: '' }
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /nieuws
        - /over-het-museum
        - /plan-je-bezoek
        - /tentoonstellingen
        - /met-je-klas-naar-het-museum
        - /collectie
        - /agenda
        - /activiteit/brugdag-museum-gesloten
        - /activiteit/luisterende-oortjes
        - /activiteit/kina-kids-insectikids
        - /nieuws/kunstproject-de-plantentuin-legt-nieuwsgierige-dieren-vast-op-camera
        - /nieuws/zeg-maar-kina
        - /nieuws/100-jaar-dit-was-het-oogstfeest
        - /privacy
        - /cookiebot-renew
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/Brussels
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: "#SG-CookieConsent\n"
    delay: 0
    scroll: false
    headers:
        - { value: '', header: '' }
    cookies: "CookieConsent={stamp:'SfuDnX8lb16A6EdWHLXnp6rL/M48Mu0ed3idL7EezUSXY8sTtzKK7A=='%2Cnecessary:true%2Cpreferences:true%2Cstatistics:true%2Cmarketing:true%2Cver:1%2Cutc:1586194359794%2Cregion:'be'}"
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
